name: Deploy to ECS

on:
  push:
    branches: [main]
    paths-ignore:
      - 'terraform/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - '/terraform/**'
  workflow_dispatch:

jobs:
  # Create the static files to website
  build:
    name: Create static files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm install
      - run: npm run build
  # Create the docker file
  create-docker-image:
    name: Build the docker image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Build the image"
