name: Terraform deployment

on:
  push:
    branches: [main]
    paths: 'terraform/**'
  pull_request:
    branches: [main]
    paths: 'terraform/**'

jobs:
  config:
    name: 'Configurate AWS and clone repo'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_ACCESS_SECRET}}
      - name: Init Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform init
        run: terraform ini
      - name: Terraform plan
        run: terraform plan
